Repository slskd/slskd, pull requests merged in 2021-11, with the labels that each got.

#238 Add serializer options to ToJson and ToObject extension methods
  src/slskd/Common/Extensions.cs
Labels: refactor

#245 Move the default configuration location to the App directory, create a Docker volume for /app
  Dockerfile
  README.md
  config/slskd.example.yml
  slskd.sln
  src/slskd/Common/Extensions.cs
  src/slskd/Integrations/FTP/FTPClientFactory.cs
  src/slskd/Integrations/FTP/FTPService.cs
  src/slskd/Options.cs
  src/slskd/Program.cs
  src/slskd/Startup.cs
  src/slskd/Transfers/API/Controllers/TransfersController.cs
  src/slskd/slskd.csproj
Labels: refactor

#263 Add option to suppress HTTP logging
  config/slskd.example.yml
  src/slskd/Options.cs
  src/slskd/Startup.cs
Labels: enhancement

#267 Retry button on failed downloads fails with a script error
  src/web/src/components/Transfers/TransferGroup.js
Labels: fix

#271 Add the ability to update the configuration file via the UI
  config/slskd.example.yml
  slskd.sln
  src/slskd/Common/Extensions.cs
  src/slskd/Common/ManagedState.cs
  src/slskd/Core/API/Controllers/ConfigurationController.cs
  src/slskd/Core/API/Controllers/OptionsController.cs
  src/slskd/Options.cs
  src/slskd/Program.cs
  src/web/package-lock.json
  src/web/package.json
  src/web/src/components/Shared/PlaceholderSegment.js
  src/web/src/components/System/Options.js
  src/web/src/components/System/Options/CodeEditor.js
  src/web/src/components/System/Options/Edit.js
  src/web/src/components/System/Options/View.js
  src/web/src/components/System/Options/index.js
  src/web/src/components/System/System.css
  src/web/src/components/System/System.js
  src/web/src/lib/options.js
Labels: feature, area: configuration

#274 Adjust release trimming options
  bin/publish
  src/slskd/slskd.csproj
Labels: fix

#275 Add transfer buffer option
  config/slskd.example.yml
  src/slskd/Application.cs
  src/slskd/Options.cs
Labels: feature

#279 Add connection write timeout option
  config/slskd.example.yml
  src/slskd/Application.cs
  src/slskd/Options.cs
  src/slskd/slskd.csproj
  src/web/package-lock.json
Labels: enhancement

#280 Add option to disable distributed children
  config/slskd.example.yml
  src/slskd/Application.cs
  src/slskd/Options.cs
Labels: enhancement

#281 Remove trimming
  src/slskd/slskd.csproj
Labels: refactor

#282 Configure TCP KeepAlive for server and distributed connections
  config/slskd.example.yml
  src/slskd/Application.cs
  src/slskd/Common/Extensions.cs
  src/slskd/Options.cs
  src/slskd/slskd.csproj
Labels: enhancement

#283 Fix bug causing failed option update
  src/slskd/Application.cs
  src/slskd/Common/Configuration/YamlConfigurationSource.cs
Labels: fix

#284 Tweak System UI
  src/slskd/Core/API/Controllers/OptionsController.cs
  src/web/src/components/Shared/CodeEditor.js
  src/web/src/components/System/Info.js
  src/web/src/components/System/Options/Edit.js
  src/web/src/components/System/Options/View.js
  src/web/src/components/System/System.css
  src/web/src/components/System/System.js
  src/web/src/lib/options.js
Labels: enhancement, area: configuration, area: ui

#285 Default remote configuration to true
  config/slskd.example.yml
  src/slskd/Core/API/Controllers/OptionsController.cs
  src/slskd/Options.cs
Labels: refactor
